server:
  port: 8081

# DATASOURCE
spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@cluster0-68qwp.mongodb.net/pdv?retryWrites=true&w=majority&connectTimeoutMS=300000&minPoolSize=1&maxPoolSize=10&maxIdleTimeMS=900000

# LOGGING
logging:
  path: pdv-log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%-level] [%-class.%-method:%line] %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%-5level{5}] [%-70class{70}.%-30method{30}] %msg%n"
  level:
    root: info
    org:
      apache: info
      springframework:
        web: info
        jdbc: info
        security: info
        hibernate:
          SQL: info
          type: info